#!/bin/bash

function wait_rabbitmq {
	while ! echo exit | nc rabbitmq 5672; do 
		sleep 1;
	done	
}

rabbitmq-server &
PID=$!
wait_rabbitmq
rabbitmqctl add_user zoe zoe
rabbitmqctl set_user_tags zoe administrator
rabbitmqctl set_permissions -p / zoe '.*' '.*' '.'
rabbitmq-plugins enable rabbitmq_management
rabbitmqctl stop
wait $PID

rabbitmq-server &
PID=$!
wait_rabbitmq
{ while true; do nc -l 9999; done } &
wait $PID
