#!/bin/bash

rabbitmq-server &
PID=$!
sleep 5
rabbitmqctl add_user zoe zoe
rabbitmqctl set_user_tags zoe administrator
rabbitmqctl set_permissions -p / zoe '.*' '.*' '.'
rabbitmq-plugins enable rabbitmq_management
rabbitmqctl stop
wait $PID

rabbitmq-server &
PID=$!
sleep 5
{ while true; do nc -l 9999; done } &
wait $PID
